### ISSUE TITLE
Bugfix InfluxDB handler

### ISSUE THREAD

**Issue by ChristianKniep** [qnib/qcollect-ng#11]
The InfluxDB handler stops sending metrics after a couple of minutes. By using this config one can see, that the opentsdb handler still emitts messages.

```
ticker:
    interval: 5000
collectors: "docker-stats,file"
filters: "id"
handlers: "influxdb,opentsdb"
collector:
  file:
    path: "resources/metrics.graphite"
    reopen: true                  # If file is truncated it will be reopened
handler:
  log:
    inputs: "id"
  influxdb:
    server: "172.17.0.1"
    inputs: "id"
  opentsdb:
    server: "172.17.0.1"
    inputs: "id"
    target: "influxdb"
```
